### ISSUE TITLE
Liferay Theme Generator fails on Yo version 5.0

### ISSUE THREAD

**Issue by ethib137** [liferay/liferay-frontend-projects#1191]
### Issue type (mark with `x`)

-   [ ] :thinking: Question
-   [x] :bug: Bug report
-   [ ] :gift: Feature request
-   [ ] :woman_shrugging: Other

### Version (mark with `x`)

-   [ ] :eight: v8.x
-   [ ] :nine: v9.x
-   [x] :keycap_ten: v10.x or higher

### Description

The Liferay Theme Generator errors out when trying to generate a theme with Yo version 5.0.

**Desired behavior:**
The theme generator should work with Yo 5.0.

**Current behavior:**
The theme generator fails with Yo 5.0

**Repro instructions (if applicable):**
If you follow the instructions in the [Readme](https://github.com/liferay/liferay-frontend-projects/tree/master/projects/js-themes-toolkit/packages/generator-liferay-theme) the following error is seen:

```
Error liferay-theme

instantiatedGenerator.run is not a function
```

**Other information (environment, versions etc):**
Downgrading to an old version of Yo fixes the issue: `npm install -g yo@4.3.1`

A similar issue is seen here: https://github.com/yeoman/generator-generator/issues/258

**Comment by bryceosterhaus** [comment]
<img width="864" alt="Screenshot 2024-01-29 at 11 59 39 AM" src="https://github.com/liferay/liferay-frontend-projects/assets/6843530/8d5b02b0-1bb0-4f53-96e0-de0a0898bb2e">

This is the compatibility matrix, so I think we just expect that it would only work with v4. We can probably specify that in the readme though

**Comment by bryceosterhaus** [comment]
Updated [READMEs](https://github.com/liferay/liferay-frontend-projects/pull/1192)

**Comment by ethib137** [comment]
Thanks Bryce! Updating the Readme is a great fix for this. Thanks.
